#insert questions
insert into questions values 
(1,'¿Cuál es un sistema operativo para pc?',1),
(2,'¿Cual es la capital de colombia?',1),
(3,'¿Cuál es el río más largo de Colombia?',1),
(4,'¿Cuál es un dispositivo de entrada?',1),
(5,'¿Cuál es un dispositivo de salida',1),
(6,'¿Cuál es el país con más habitantes del mundo?',2),
(7,'¿Cuál es el edificio más alto del mundo?',2),
(8,'¿Dónde está Transilvania?',2),
(9,'¿Cuál es el país con menos habitantes del mundo?',2),
(10,'¿Cuál es la película con más Óscars de la historia del cine?',2),
(11,'¿En qué año cayó el muro de Berlín?',3),
(12,'¿Cuántos años duró la Primera Guerra Mundial?',3),
(13,'¿Cuántos años duró la Segunda Guerra Mundial?',3),
(14,'¿Cuál es el futbolista con más balones de oro?',3),
(15,'¿Quién ganó el mundial de fútbol de 2010?',3),
(16,'¿Cuáles son los únicos mamíferos que pueden volar?',4),
(17,'¿Cuál es el álbum musical más vendido de la historia?',4),
(18,'¿Cuál es el animal más grande de la Tierra?',4),
(19,'¿Cuántos huesos tiene el cuerpo humano?',4),
(20,'¿Cuál es el planeta más grande del Sistema Solar?',4),
(21,'¿Cuál es el animal que más muertes provoca cada año?',5),
(22,'¿Cuál es el atleta con más medallas olímpicas?',5),
(23,'¿Cuándo llegó Cristóbal Colón a América?',5),
(24,'¿Cuál es el himno de la Unión Europea?',5),
(25,'¿Cuándo murió Freddie Mercury?',5);